apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enterprise-system-20260620-135117-b88sfz7op7vs-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: enterprise-system-20260620-135117-b88sfz7op7vs.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: enterprise-system-20260620-135117-b88sfz7op7vs-service
            port:
              number: 80
